### ISSUE TITLE
`safergpy/README.md`: Bad example

### ISSUE THREAD

**Issue by jbect** [saferGPMLE/saferGPMLE#11]
The example in `safergpy/README.md` is
```
python3 plot_error_cdf_benchmark.py --solid-lines gpy_mle0000 stk261_matR2019b_mle1000 --dashed-lines gpy_mle0010 gpy_mle001
```
which is very unlikely to work since we have no STK-related data in our results :wink:

**Comment by Subhasishbasak** [comment]
@johncoltrane1 do we really need to provide the sanity check example for the script `plot_error_cdf_benchmark.py`?

**Comment by jbect** [comment]
@Subhasishbasak does this commit: https://github.com/saferGPMLE/saferGPMLE/commit/7c1d2d70707af0f48a65898b231cd09f4019a70a answer your question?
